version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
      exclude-functions:
        - fmt.Fprintf
        - fmt.Fprintln
        - (github.com/jtzemp/dogfetch/internal/writer.Writer).Close
        - (*os.File).Close
        - os.Remove
        - (*encoding/json.Encoder).Encode